{{- if .Values.overview.enabled }}
apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: composition-{{ .Release.Name }}-tabpane-overview-row-column-1-panel
  namespace: {{ .Release.Namespace }}
spec:
  type: panel
  widgetsRefs:
  {{- range $i, $e := until (len .Values.overview.text)}}
    - apiVersion: templates.krateo.io/v1alpha1
      resource: widgets
      name: composition-{{ $.Release.Name }}-tabpane-overview-row-column-1-panel-paragraph-{{$i}}
      namespace: {{ $.Release.Namespace }}
  {{- end }}
{{- $i := 0 | int }}
{{- range .Values.overview.text }}
---
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: composition-{{ $.Release.Name }}-tabpane-overview-row-column-1-panel-paragraph-{{$i}}
  namespace: {{ $.Release.Namespace }}
spec:
  type: paragraph
  app:
    template:
      text: {{ . }}
  {{- $i = add1 $i }}
  {{- end }}
{{- end }}